#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_inspec="$(inspec version 2>/dev/null || true)"
  jq -n --arg inspec "$ver_inspec" '{inspec: $inspec}'
}

version "$@"
